export interface SectionZone {
  id: string;
  name: string;
  carnivalName: string;
  emoji: string;
  feeling: string;
  theme: string;
  color: number; // Phaser hex color
  lightColor: string; // CSS color
  x: number;
  y: number;
  width: number;
  height: number;
  description: string;
}

export const WORLD_WIDTH = 3200;
export const WORLD_HEIGHT = 2400;

export const SECTIONS: SectionZone[] = [
  {
    id: 'selfcare',
    name: 'Self-care',
    carnivalName: 'The Cozy Spa Tent',
    emoji: '🌸',
    feeling: 'I need to love myself',
    theme: 'theme-selfcare',
    color: 0xFFB8D4,
    lightColor: '#FFF0F6',
    x: 300, y: 1500, width: 260, height: 200,
    description: 'A glowing lantern tent of rest & renewal',
  },
  {
    id: 'anxiety',
    name: 'Tea with Anxiety',
    carnivalName: 'The Tea Café',
    emoji: '☕',
    feeling: 'I need to ease my anxiety',
    theme: 'theme-anxiety',
    color: 0xB8D4FF,
    lightColor: '#F0F5FF',
    x: 320, y: 1100, width: 280, height: 220,
    description: 'Invite your anxiety in for a cup of tea',
  },
  {
    id: 'creativity',
    name: 'Creativity & Inner Child',
    carnivalName: 'The Art Corner',
    emoji: '🎨',
    feeling: 'I need to feel creative',
    theme: 'theme-creativity',
    color: 0xFFD4B8,
    lightColor: '#FFF8F0',
    x: 250, y: 700, width: 280, height: 220,
    description: 'Giant canvases, paint, and stories waiting to be told',
  },
  {
    id: 'socialmedia',
    name: 'Social Media Break',
    carnivalName: 'The Unplugged Booth',
    emoji: '📵',
    feeling: 'I need a break from digital chaos',
    theme: 'theme-socialmedia',
    color: 0xD4B8FF,
    lightColor: '#F5F0FF',
    x: 850, y: 350, width: 270, height: 200,
    description: 'Retro games, dot-to-dot, and analog fun',
  },
  {
    id: 'burnout',
    name: 'Burnout',
    carnivalName: 'The Campfire Chill Zone',
    emoji: '🕯️',
    feeling: 'I need to feel rested & renewed',
    theme: 'theme-burnout',
    color: 0xFFE5B8,
    lightColor: '#FFFAF0',
    x: 1400, y: 300, width: 270, height: 200,
    description: 'Slow down, refill your tank, and breathe',
  },
  {
    id: 'grounding',
    name: 'Grounding',
    carnivalName: 'The Sensory Garden',
    emoji: '🌿',
    feeling: 'I need to feel grounded & steady',
    theme: 'theme-grounding',
    color: 0xB8FFD4,
    lightColor: '#F0FFF8',
    x: 1950, y: 350, width: 260, height: 200,
    description: 'The 5-4-3-2-1 nature experience',
  },
  {
    id: 'acceptance',
    name: 'Acceptance',
    carnivalName: 'The Pink Elephant Exhibit',
    emoji: '🐘',
    feeling: 'I need to accept things as they are',
    theme: 'theme-acceptance',
    color: 0xFFB8F0,
    lightColor: '#FFF0FD',
    x: 2500, y: 500, width: 260, height: 200,
    description: 'A whimsical tent with the famous pink elephant',
  },
  {
    id: 'goals',
    name: 'Goals & Dreams',
    carnivalName: 'The Hot Air Balloon Launch',
    emoji: '🎈',
    feeling: 'I need to chase my dreams',
    theme: 'theme-goals',
    color: 0xFFF5B8,
    lightColor: '#FFFFF0',
    x: 2700, y: 900, width: 270, height: 220,
    description: 'Vision boards, mind maps, and shooting stars',
  },
  {
    id: 'habits',
    name: 'Habit Formation',
    carnivalName: 'The Token Arcade',
    emoji: '🎮',
    feeling: 'I need to build habits that feel good',
    theme: 'theme-habits',
    color: 0xB8FFFF,
    lightColor: '#F0FFFF',
    x: 2750, y: 1300, width: 260, height: 200,
    description: 'Earn tokens for every good habit you keep',
  },
  {
    id: 'flow',
    name: 'The Joy of Flow',
    carnivalName: 'The Flow Carousel',
    emoji: '🎠',
    feeling: 'I need to find my flow',
    theme: 'theme-flow',
    color: 0xB8D4FF,
    lightColor: '#F0F5FF',
    x: 2700, y: 1750, width: 280, height: 200,
    description: 'Lose yourself in the things that make time fly',
  },
  {
    id: 'forgiveness',
    name: 'Forgiveness & Letting Go',
    carnivalName: 'The Balloon Release Station',
    emoji: '🕊️',
    feeling: 'I need to let go & find peace',
    theme: 'theme-forgiveness',
    color: 0xD4FFB8,
    lightColor: '#F5FFF0',
    x: 2200, y: 1900, width: 270, height: 200,
    description: 'Write your letters and watch them float away',
  },
  {
    id: 'gratitude',
    name: 'Gratitude',
    carnivalName: 'The Wishing Well',
    emoji: '🪴',
    feeling: 'I need to focus on little moments of joy',
    theme: 'theme-gratitude',
    color: 0xFFD4B8,
    lightColor: '#FFF8F0',
    x: 1550, y: 1950, width: 260, height: 200,
    description: 'Fill your gratitude jar, one note at a time',
  },
  {
    id: 'friendships',
    name: 'Navigating Adult Friendships',
    carnivalName: 'The Friendship Garden',
    emoji: '🌻',
    feeling: 'I need a sense of belonging',
    theme: 'theme-friendships',
    color: 0xFFB8B8,
    lightColor: '#FFF5F5',
    x: 900, y: 1900, width: 270, height: 200,
    description: 'Grow a garden of the people you love',
  },
  {
    id: 'lovelife',
    name: 'Love Life',
    carnivalName: 'The Heart Ferris Wheel',
    emoji: '💕',
    feeling: 'I need clarity in my love life',
    theme: 'theme-lovelife',
    color: 0xFFB8D4,
    lightColor: '#FFF0F6',
    x: 350, y: 1900, width: 260, height: 200,
    description: 'Explore your heart, heal, and keep going',
  },
  {
    id: 'shop',
    name: 'The Bookstore',
    carnivalName: 'The Bookstore',
    emoji: '📖',
    feeling: 'I want the physical book',
    theme: 'theme-selfcare',
    color: 0xFFF5B8,
    lightColor: '#FFFFF0',
    x: 1400, y: 1100, width: 300, height: 220,
    description: 'Order your hard copy of Get Lost in the Right Direction',
  },
];

export const PANDA_START = { x: 1600, y: 1700 };
